# Generated by Django 6.0.2 on 2026-02-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
