# Generated by Django 6.0.2 on 2026-02-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0003_remove_payment_status_remove_swaprequest_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
