# Generated by Django 6.0.2 on 2026-02-24 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillapp', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
    ]
